### ISSUE TITLE
Constantly decreasing pressure ?

### ISSUE THREAD

**Issue by YordanYanakiev** [enjoyneering/BMP180#1]
Hello.
I am stumbling upon the follow issue : 
I am measuring the pressure each 1 second, and seems like the pressure readings constantly dropping.
What could be the cause of this issue ?

**Comment by enjoyneering** [comment]
Sorry for delay,

I have never had this problem. Have you followed the recommendations?
- Do not expose the BMP180 excessively to the airflow of a fan, as this may result in erroneous or very fluctuating measurements.
- The measurement of the atmospheric pressure depends on the temperature. Avoid placing the BMP180 in front of a source of heat, still less in front of a source producing rapid changes (heating, window in full sun …).
- The BMP180 is sensitive to moisture and is not intended for direct contact with water.
- It is also sensitive to light. It should be protected as much as possible from ambient light. Do not place the sensor in front of the ventilation hole of your case, for example.

**Comment by YordanYanakiev** [comment]
Owww. I didn't knew this. Thank You! :)
